USE [10.11HW]
GO

/****** Object:  Table [dbo].[PetInfo]    Script Date: 10/11/2016 9:10:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PetInfo](
	[AnimalSpeices] [varchar](50) NULL,
	[Breed] [varchar](50) NULL,
	[Gender] [nchar](10) NOT NULL,
	[Age] [int] NULL,
	[Chipped] [nchar](10) NOT NULL,
	[PetID] [int] NOT NULL,
 CONSTRAINT [PK_FamInfo] PRIMARY KEY CLUSTERED 
(
	[PetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PetInfo]  WITH CHECK ADD  CONSTRAINT [FK_PetInfo_FamInfo] FOREIGN KEY([PetID])
REFERENCES [dbo].[FamInfo] ([PetID])
GO

ALTER TABLE [dbo].[PetInfo] CHECK CONSTRAINT [FK_PetInfo_FamInfo]
GO

ALTER TABLE [dbo].[PetInfo]  WITH CHECK ADD  CONSTRAINT [FK_PetInfo_FamPreInfo] FOREIGN KEY([PetID])
REFERENCES [dbo].[FamPreInfo] ([PetID])
GO

ALTER TABLE [dbo].[PetInfo] CHECK CONSTRAINT [FK_PetInfo_FamPreInfo]
GO

